In [85]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Ejercicio 1
matriz1=np.array([[0,-6],[5,4]])
def normal0(matriz):
    l0=np.sum(matriz!=0)
    return l0

def normal1(matriz):
    l1=np.sum(abs(matriz))
    return l1

def normal2(matriz):
    l2=np.sqrt(np.sum(abs(matriz)**2))
    return l2

def normainf(matriz):
    linf=np.max(abs(matriz))
    return linf

In [3]:
print("La norma l0 de la matriz es:",normal0(matriz1))
print("La norma l1 de la matriz es:",normal1(matriz1))
print("La norma l2 de la matriz es:",normal2(matriz1))
print("La norma l infinito de la matriz es:",normainf(matriz1))

La norma l0 de la matriz es: 3
La norma l1 de la matriz es: 15
La norma l2 de la matriz es: 8.774964387392123
La norma l infinito de la matriz es: 6


In [4]:
# Ejercicio 2
def normal2_con_axis(matriz,axis):
    l2=np.sqrt(np.sum(abs(matriz)**2,axis=axis))
    return l2

normas_ordenadas = np.argsort(normal2_con_axis(matriz1,1)[::-1])
print("Orden de las normas:",normas_ordenadas)
matriz1_ordenada=matriz1[normas_ordenadas]
print("Matriz 1 ordenada por fila según la norma l2",matriz1_ordenada)

Orden de las normas: [1 0]
Matriz 1 ordenada por fila según la norma l2 [[ 5  4]
 [ 0 -6]]


In [5]:
#Ejercicio 3
class array_ids:
    def __init__(self, ids):
        indexes = np.unique(ids, return_index=True)[1]
        ids_unicos = [ids[index] for index in sorted(indexes)]        
        
    def get_users_id(self, user_idx):
        try:
            user_id = ids_unicos[user_idx]
        except:
            user_id = -1
        return user_id
    
    def get_users_idx(self, user_id):
        try:
            user_idx = list(ids_unicos).index(user_id)
        except:
            user_idx = -1
        return user_idx

In [6]:
array1 = [1,4,3,2,5,3]

In [7]:
array_id_object = array_ids(array1)

In [8]:
array_id_object.get_users_idx(4)

-1

In [9]:
array_id_object.get_users_id(1)

-1

In [10]:
#Ejercicio 4
%time
truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

suma = truth+prediction
resta = truth-prediction
TP=len(suma[suma==2])
TN=len(suma[suma==0])
FN=len(suma[resta==1])
FP=len(suma[resta==(-1)])

Precision = TP / (TP + FP)
Recall = TP / (TP + FN)
Accuracy = (TP + TN) / (TP + TN + FP + FN)

print(TP)
print(TN)
print(FN)
print(FP)

print("Precision:",Precision)
print("Recall",Recall)
print("Accuracy",Accuracy)

Wall time: 0 ns
3
1
3
3
Precision: 0.5
Recall 0.5
Accuracy 0.4


In [11]:
#Ejercicio 5
q_id = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]) 
predicted_rank = np.array([0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3]) 
truth_relevance = np.array([True, False, True, False, True, True, True, False, False, False, False, False, True, False, False, True])

In [12]:
q_id_list=list(q_id)

truth_1=truth_relevance[q_id_list.index(1):q_id_list.index(1)+len(q_id[q_id==1])]

truth_2=truth_relevance[q_id_list.index(2):q_id_list.index(2)+len(q_id[q_id==2])]

truth_3=truth_relevance[q_id_list.index(3):q_id_list.index(3)+len(q_id[q_id==3])]

truth_4=truth_relevance[q_id_list.index(4):q_id_list.index(4)+len(q_id[q_id==4])]


In [13]:
Precision_1 = np.sum(truth_1)/len(truth_1)
Precision_2 = np.sum(truth_2)/len(truth_2)
Precision_3 = np.sum(truth_3)/len(truth_3)
Precision_4 = np.sum(truth_4)/len(truth_4)
AQP = np.mean(np.array([Precision_1,Precision_2,Precision_3,Precision_4]))
print(Precision_1)
print(Precision_2)
print(Precision_3)
print(Precision_4)
print("AQP",AQP)

0.5
1.0
0.0
0.5
AQP 0.5


In [14]:
#Ejercicio 6 (Ejercicio resuelto por Lautaro)
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C = np.array([[1, 0, 0], [0, 1, 1]])

def get_centroid_distances(C, X):
    expanded_C = C[:, None]
    distances = np.sqrt(np.sum((expanded_C - X) ** 2, axis=2))
    return distances


In [20]:
distancias = get_centroid_distances(C,X)
print(distancias)

[[ 3.60555128  8.36660027 13.45362405]
 [ 2.44948974  7.54983444 12.72792206]]


In [16]:
X.shape

(3, 3)

In [17]:
C.shape

(2, 3)

In [18]:
expanded_C = C[:, None]
expanded_C.shape

(2, 1, 3)

In [19]:
print((expanded_C - X))
print((expanded_C - X).shape)
print(np.sum((expanded_C - X),axis=2))
print((np.sum((expanded_C - X),axis=2)).shape)

[[[ 0 -2 -3]
  [-3 -5 -6]
  [-6 -8 -9]]

 [[-1 -1 -2]
  [-4 -4 -5]
  [-7 -7 -8]]]
(2, 3, 3)
[[ -5 -14 -23]
 [ -4 -13 -22]]
(2, 3)


In [25]:
# Ejercicio 7
id_clusters = np.argmin(distancias, axis=0)

In [79]:
#Ejercicio 8
def k_means(X, n):
    centroides = X[np.random.choice(np.arange(X.shape[0]),size=n,replace = False)]
    distancias = get_centroid_distances(centroides,X)
    id_clusters = np.argmin(distancias, axis=0)
    for i in range(10): #Elegimos hacer 10 iteraciones de recálculo de centroides
        # redeterminar los centroides -> Tomado de Lautaro
        for i in range(centroides.shape[0]):
            # cada centroide i lo recalculo como la media de todos los vectores X que tengan como id_cluster a ese centroide
            centroides[i] = np.mean(X[id_clusters == i, :], axis=0)

    return centroides

In [84]:
X = (5*np.random.random(size=1000)).reshape(100,10)
k_means(X,5)


array([[3.68830659, 1.0639306 , 3.98537028, 3.24854261, 2.21015793,
        2.87419166, 2.04271654, 2.75077796, 2.6421841 , 2.31047921],
       [1.92513914, 2.74759078, 1.95443062, 2.50745193, 1.2677928 ,
        1.6504626 , 2.81758416, 3.66777792, 1.70953132, 3.58004422],
       [2.47166037, 2.84425851, 4.0517224 , 2.07598983, 1.7537255 ,
        2.73277276, 1.85204556, 2.01918128, 2.72806235, 1.76469867],
       [1.97696912, 2.22423264, 1.82851734, 3.22956425, 2.17410097,
        3.43901265, 2.98916347, 1.93558635, 2.92208109, 2.99699173],
       [2.53906604, 2.5510891 , 2.17159362, 2.15925639, 3.16012806,
        1.39377064, 3.09213944, 2.3579966 , 3.17237137, 2.46862773]])

In [ ]:
#Ejercicio 9

In [ ]:
#Ejercicio 10